_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: True
  MASKIOU_ON: False
  MASK_EEE_ON: True
  ROI_MASK_HEAD:
    MASK_EEE_ON: True

SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.0025
  STEPS: (180000, 240000)
  MAX_ITER: 270000
  CHECKPOINT_PERIOD: 90000
TEST:
  EVAL_PERIOD: 10
DATASETS:
  TRAIN: ("coco_2017_val",)
  TEST: ("coco_2017_val",)